### ISSUE TITLE
Correzione ed ampliamento dei requisiti

### ISSUE THREAD

**Issue by danielcontro** [Spaghetti-Code-G6/Documenti#85]
# TODO:
- [ ] controllare che i requisiti precedentemente scritti siano ancora validi
- [ ] ampliare con i nuovi requisiti aggiunti
- [ ] aggiungere le fonti
- [ ] aggiornare il tracciamento di conseguenza
